services:

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/nginx.conf:ro
    networks:
      - node_network
    depends_on:
      - node-app

  node-app:
    build: .
    volumes:
      - ./:/app:ro
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - SESSION_SECRET=secret
      - REDIS_HOST=redis_container
      - REDIS_PORT=6379
    env_file:
      - ./.env
    networks:
      - node_network

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongo-db:/data/db

  redis_container: 
    image: redis
    ports:
      - 6379:6379

volumes:
  mongo-db:

networks:
  node_network: