services:
  node-app:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app:ro
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - SESSION_SECRET=secret
      - REDIS_HOST=redis_container
      - REDIS_PORT=6379
    env_file:
      - ./.env

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - mongo-db:/data/db

  redis_container: 
    image: redis
    ports:
      - 6379:6379

volumes:
  mongo-db: